/** Shared agent ids — keep in sync with backend/app/company.py TEAMS.members */

export const TEAM_IDS = {
  creative: 'creative',
  legal_business: 'legal_business',
  science_medical: 'science_medical',
  news_media: 'news_media',
  master: 'master',
};

export const TEAM_MEMBERS = {
  creative: ['creative-1', 'creative-2'],
  legal_business: ['legal-1', 'legal-2'],
  science_medical: ['science-1', 'science-2'],
  news_media: ['news-1', 'news-2'],
  master: ['master'],
};

/** Fixed 16-colour Stardew-modern palette */
export const PALETTE = {
  cream: '#f7f0e4',
  paper: '#fffcf6',
  ink: '#3b2f2a',
  inkSoft: '#6f6159',
  muted: '#9a8b7f',
  line: '#eadfce',
  lineStrong: '#dccdb7',
  terracotta: '#c8643b',
  terracottaDark: '#a94f2c',
  sage: '#6e9a74',
  sageSoft: '#e5efe3',
  honey: '#e7b45a',
  honeySoft: '#fbf0d9',
  wood: '#6b4a33',
  night: '#2a1f1b',
  sky: '#bfe3f2',
  white: '#ffffff',
  blush: '#f0c4b0',
  leaf: '#4f7a55',
  monitor: '#3a5a6e',
  monitorGlow: '#9ad4ef',
  carpet: '#d4a574',
  rugCreative: '#e8b4c8',
  rugLegal: '#a8c0d8',
  rugScience: '#b8d4a8',
  rugNews: '#e8c878',
};

export const TEAM_TITLES = {
  creative: 'Creative Studio',
  legal_business: 'Legal & Business',
  science_medical: 'Science & Medical',
  news_media: 'News & Media',
  master: 'Master Translator',
};

/**
 * Every figure that lives on the office floor.
 * seat keys map into layout.js SEATS.
 */
export const ROSTER = [
  {
    id: 'manager',
    name: 'Manager',
    title: 'Manager',
    role: 'manager',
    seat: 'manager',
    hair: '#3b2f2a',
    shirt: '#c8643b',
    pants: '#3b2f2a',
    skin: '#f0c4b0',
  },
  {
    id: 'editor',
    name: 'Editor',
    title: 'Editor',
    role: 'editor',
    seat: 'editor',
    hair: '#6b4a33',
    shirt: '#6e9a74',
    pants: '#3b2f2a',
    skin: '#e8b898',
  },
  {
    id: 'master',
    name: 'Master Translator',
    title: 'Master Translator',
    role: 'translator',
    team: 'master',
    seat: 'master',
    hair: '#c8c0b4',
    shirt: '#6b4a33',
    pants: '#3b2f2a',
    skin: '#e0b090',
    glasses: true,
    senior: true,
  },
  {
    id: 'creative-1',
    name: 'Translator #1',
    title: 'Literary',
    role: 'translator',
    team: 'creative',
    seat: 'creative-1',
    hair: '#a94f2c',
    shirt: '#e8b4c8',
    pants: '#6b4a33',
    skin: '#f0c4b0',
  },
  {
    id: 'creative-2',
    name: 'Translator #2',
    title: 'Marketing',
    role: 'translator',
    team: 'creative',
    seat: 'creative-2',
    hair: '#3b2f2a',
    shirt: '#c8643b',
    pants: '#6f6159',
    skin: '#d4a078',
  },
  {
    id: 'legal-1',
    name: 'Translator #1',
    title: 'Legal',
    role: 'translator',
    team: 'legal_business',
    seat: 'legal-1',
    hair: '#3b2f2a',
    shirt: '#a8c0d8',
    pants: '#2a1f1b',
    skin: '#f0c4b0',
  },
  {
    id: 'legal-2',
    name: 'Translator #2',
    title: 'Business',
    role: 'translator',
    team: 'legal_business',
    seat: 'legal-2',
    hair: '#6b4a33',
    shirt: '#6f6159',
    pants: '#2a1f1b',
    skin: '#e8b898',
  },
  {
    id: 'science-1',
    name: 'Translator #1',
    title: 'Science',
    role: 'translator',
    team: 'science_medical',
    seat: 'science-1',
    hair: '#3b2f2a',
    shirt: '#b8d4a8',
    pants: '#6b4a33',
    skin: '#f0c4b0',
  },
  {
    id: 'science-2',
    name: 'Translator #2',
    title: 'Medical',
    role: 'translator',
    team: 'science_medical',
    seat: 'science-2',
    hair: '#9a8b7f',
    shirt: '#6e9a74',
    pants: '#3b2f2a',
    skin: '#d4a078',
  },
  {
    id: 'news-1',
    name: 'Translator #1',
    title: 'News',
    role: 'translator',
    team: 'news_media',
    seat: 'news-1',
    hair: '#3b2f2a',
    shirt: '#e8c878',
    pants: '#6b4a33',
    skin: '#f0c4b0',
  },
  {
    id: 'news-2',
    name: 'Translator #2',
    title: 'Media',
    role: 'translator',
    team: 'news_media',
    seat: 'news-2',
    hair: '#a94f2c',
    shirt: '#e7b45a',
    pants: '#3b2f2a',
    skin: '#e8b898',
  },
  {
    id: 'terminologist',
    name: 'Terminologist',
    title: 'Terminologist',
    role: 'terminologist',
    seat: 'terminologist',
    hair: '#6b4a33',
    shirt: '#9ad4ef',
    pants: '#3b2f2a',
    skin: '#f0c4b0',
  },
  {
    id: 'receptionist',
    name: 'Receptionist',
    title: 'Reception',
    role: 'receptionist',
    seat: 'reception',
    hair: '#c8643b',
    shirt: '#e7b45a',
    pants: '#6b4a33',
    skin: '#f0c4b0',
  },
  {
    id: 'client',
    name: 'Client',
    title: 'Client',
    role: 'client',
    seat: 'door',
    hair: '#3b2f2a',
    shirt: '#6f6159',
    pants: '#2a1f1b',
    skin: '#e8b898',
  },
];

export const ROSTER_BY_ID = Object.fromEntries(ROSTER.map((r) => [r.id, r]));

export function workersForTeam(teamId) {
  return TEAM_MEMBERS[teamId] || TEAM_MEMBERS.master;
}
